### ISSUE TITLE
Delegates for FIAT payment for crypto TX

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/pm#170]
A working delegate model would help keep underlying utility tokens for payments while abstracting the need to hold them. A custodian or intermediary would accept FIAT payments to pay the fees and price for access. This would remove barriers for conventional enterprises.
Why is the delegate model important for adoption? It adds a lot / removes entry barriers from the onboarding flow to increase active user numbers.

Additionally the delegate model can be quite an attractive business model.

To add on privacy the ability to use multisig accounts during publication and consumption is equally important as it would allow to abstract a “personal” identity of a natural person / employee away from the TX which makes usage more GDPR-compliant, which - if not implemented - could make it a showstopper in some cases.

**Comment by kaimeinke** [comment]
This is closely related to https://github.com/oceanprotocol/pm/issues/169 and aims to implement a delegate solution. This is preferred by many institutional actors as regulatory firewall and due to the fact that accounting does not have to make large changes to their processes. This has been stressed by many institutional actors and is the widely accepted approach, i.e. MetaMask Institutional and other Custodians. The base layer can remain largely untouched while the consumer can simply consume services and pay via any preferred payment option and without the need to think further in terms of compliance. 

Utility: Drives adoption, increases compliance and user experience.
